#!/bin/bash
go build ./callbacks/types_of_callbacks/main.go >/dev/null 2>&1 ; echo "./callbacks/types_of_callbacks/main.go: $?"
go build ./callbacks/main.go >/dev/null 2>&1 ; echo "./callbacks/main.go: $?"
go build ./context/main.go >/dev/null 2>&1 ; echo "./context/main.go: $?"
go build ./agents/custom-agent/storyflow_agent.go >/dev/null 2>&1 ; echo "./agents/custom-agent/storyflow_agent.go: $?"
go build ./agents/models/models.go >/dev/null 2>&1 ; echo "./agents/models/models.go: $?"
go build ./agents/llm-agents/snippets/main.go >/dev/null 2>&1 ; echo "./agents/llm-agents/snippets/main.go: $?"
go build ./agents/llm-agents/main.go >/dev/null 2>&1 ; echo "./agents/llm-agents/main.go: $?"
go build ./agents/workflow-agents/parallel/main.go >/dev/null 2>&1 ; echo "./agents/workflow-agents/parallel/main.go: $?"
go build ./agents/workflow-agents/sequential/main.go >/dev/null 2>&1 ; echo "./agents/workflow-agents/sequential/main.go: $?"
go build ./agents/workflow-agents/loop/main.go >/dev/null 2>&1 ; echo "./agents/workflow-agents/loop/main.go: $?"
go build ./agents/multi-agent/main.go >/dev/null 2>&1 ; echo "./agents/multi-agent/main.go: $?"
go build ./artifacts/main.go >/dev/null 2>&1 ; echo "./artifacts/main.go: $?"
go build ./tools/function-tools/func_tool.go >/dev/null 2>&1 ; echo "./tools/function-tools/func_tool.go: $?"
go build ./tools/function-tools/long-running-tool/long_running_tool.go >/dev/null 2>&1 ; echo "./tools/function-tools/long-running-tool/long_running_tool.go: $?"
go build ./tools/built-in-tools/google_search.go >/dev/null 2>&1 ; echo "./tools/built-in-tools/google_search.go: $?"